{
 "title": "HW3",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (instance) (rate(node_cpu_seconds_total{mode !='idle'}[5m])) * 100\n",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{} - node_memory_MemFree_bytes{} - \nnode_memory_Cached_bytes{} - \nnode_memory_Buffers_bytes{}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by (instance) (irate(django_http_requests_total_by_view_transport_method_total{view!~\"prometheus-django-metrics|healthcheck\"}[1m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Request Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(django_http_requests_latency_seconds_by_view_method_bucket{view!~\"prometheus-django-metrics|healthcheck\"}[5m])) by (instance, le))",
     "legendFormat": "{{instance}} quantile=50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(django_http_requests_latency_seconds_by_view_method_bucket{view!~\"prometheus-django-metrics|healthcheck\"}[5m])) by (instance, le))",
     "legendFormat": "{{instance}} quantile=95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(django_http_requests_latency_seconds_by_view_method_bucket{view!~\"prometheus-django-metrics|healthcheck\"}[5m])) by (instance, le))",
     "legendFormat": "{{instance}} quantile=99"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(django_http_requests_latency_seconds_by_view_method_bucket{view!~\"prometheus-django-metrics|healthcheck\"}[5m])) by (instance, le))",
     "legendFormat": "{{instance}} quantile=99,9"
    }
   ]
  },
  {
   "title": "Network receive",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (instance) (irate(node_network_receive_bytes_total{}[1m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Network transmit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (instance) (irate(node_network_transmit_bytes_total{}[1m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Available Space",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (instance) (node_filesystem_avail_bytes{})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Used Space",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (instance) (node_filesystem_size_bytes{} - node_filesystem_avail_bytes{})",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}