global:
  scrape_interval:     10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: server_1
    static_configs:
      - targets:
        - '35.228.238.213:80'
        - '35.228.238.213:9100'

  - job_name: server_2
    static_configs:
      - targets:
        - '35.228.112.253:80'
        - '35.228.112.253:9100'

  - job_name: server_3
    static_configs:
      - targets:
        - '34.88.155.225:80'
        - '34.88.155.225:9100'